name: Check Automerge

on:
  pull_request_target:

permissions: write-all
#  pull-requests: write

jobs:
  setautomerge:
    name: Set Automerge
    runs-on: ubuntu-latest
    if: github.actor == 'dopplershift'

    steps:
      - name: Check changed files
        id: checkpath
        uses: dorny/paths-filter@v2.10.1
        with:
          filters: |
            ci:
              - 'ci/linting_requirements.txt'

      - name: Set Automerge
        if: steps.checkpath.outputs.ci == 'true'
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const query = `query GetPullRequestId($owner: String!, $repo: String!, $pullRequestNumber: Int!) {
              repository(owner: $owner, name: $repo) {
                pullRequest(number: $pullRequestNumber) {
                  id
                }
              }
            }`
            const params = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pullRequestNumber: context.payload.number
            };
            const id_resp = await github.graphql(query, params);
            console.log(id_resp);
            const merge_params = {
              pullRequestId: id_resp.repository.pullRequest.id,
              mergeMethod: 'MERGE'
            };
            const mutation_query = `mutation ($pullRequestId: ID!, $mergeMethod: PullRequestMergeMethod!) {
              enablePullRequestAutoMerge(input: {
                pullRequestId: $pullRequestId,
                mergeMethod: $mergeMethod
              }) {
                pullRequest {
                  autoMergeRequest {
                    enabledAt
                    enabledBy {
                      login
                    }
                  }
                }
              }
            }`
            const resp = await github.graphql(mutation_query, merge_params);
            console.log(response.enablePullRequestAutoMerge.pullRequest.autoMergeRequest);
