name: Check Automerge

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  setautomerge:
    name: Set Automerge
    runs-on: ubuntu-latest
    if: github.actor == 'dopplershift'

    steps:
      - name: Check changed files
        id: checkpath
        uses: dorny/paths-filter@v2.10.1
        with:
          filters: |
            ci:
              - 'ci/linting_requirements.txt'

      - name: Set Automerge
        if: steps.checkpath.outputs.ci == 'true'
        run: echo Setting automerge...