name: Run Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    # - name: Set up caching
    #   uses: actions/cache@v3
    #   id: cache-proj
    #   with:
    #     path: ~/local
    #     key: proj-${{ runner.os }}-8.1.1-0

    # - name: Write value
    #   if: steps.cache-proj.outputs.cache-hit != 'true'
    #   run: |
    #     mkdir ~/local
    #     echo 3.14159 > ~/local/pi.txt


    - name: Setup PyPI
      uses: Unidata/MetPy/.github/actions/install-pypi@main
      with:
        need-cartopy: true
        type: test
        version-file: requirements.txt
        python-version: '3.10'

    - name: Tests
      run: sleep 10

