name: Manage doc versions

on:
  push:
    branches:
      - gh-pages
    paths-ignore:
      - 'dev/**'

jobs:
  doc-versions:
    name: Handle new version of docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - name: Install packaging
      run: python -m pip install packaging

      - name: Update versions
      run: python versions.py

    - name: Commit changes
      run: |
        git commit -am "Update version information"
        git push
