name: Add comment
on:
  pull_request:
    types:
      - labeled
jobs:
  label-run:
    if: github.event.label.name == 'run-ci'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Tests
      run: sleep 30